name: Fun Greet

on:
  push:

jobs:
  fun-greet:
    runs-on: ubuntu-latest
    steps:
      - name: Fun Echo
        run: |
          echo "ğŸ Keep coding!"
          echo "ğŸš€ Push Received!"
          echo "ğŸ”¥ Stay Awesome!"
